"""empty message

Revision ID: 1bba9b5cbbef
Revises: d8e5a70ed28
Create Date: 2015-05-02 20:21:19.496494

"""

# revision identifiers, used by Alembic.
revision = '1bba9b5cbbef'
down_revision = 'd8e5a70ed28'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('district_kr_idx', 'kaharesource', ['district'], unique=False)
    op.create_index('resource_type_idx', 'kaharesource_type', ['resource_type'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('resource_type_idx', table_name='kaharesource_type')
    op.drop_index('district_kr_idx', table_name='kaharesource')
    ### end Alembic commands ###
