"""empty message

Revision ID: 374fdffb9bb5
Revises: None
Create Date: 2015-05-08 19:46:48.205620

"""

# revision identifiers, used by Alembic.
revision = '374fdffb9bb5'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kaha_location',
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(length=200), nullable=True),
    sa.Column('district', sa.String(length=200), nullable=True),
    sa.Column('district_code', sa.Integer(), nullable=True),
    sa.Column('vdc_name', sa.String(length=250), nullable=True),
    sa.Column('vdc_code', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('location_id'),
    sa.UniqueConstraint('vdc_code')
    )
    op.create_index('district_name_idx', 'kaha_location', ['district'], unique=False)
    op.create_index('district_vdc_idx', 'kaha_location', ['vdc_name'], unique=False)
    op.create_table('kaharesource',
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=50), nullable=True),
    sa.Column('resource_for', sa.String(length=10), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('district', sa.String(length=150), nullable=True),
    sa.Column('district_code', sa.Integer(), nullable=True),
    sa.Column('vdc_code', sa.Integer(), nullable=True),
    sa.Column('tole', sa.String(length=150), nullable=True),
    sa.Column('contactname', sa.String(length=200), nullable=True),
    sa.Column('contactnumber', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['kaha_location.location_id'], ),
    sa.PrimaryKeyConstraint('resource_id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('created_kr_idx', 'kaharesource', ['created'], unique=False)
    op.create_index('district_kr_idx', 'kaharesource', ['district'], unique=False)
    op.create_index('updated_kr_idx', 'kaharesource', ['updated'], unique=False)
    op.create_table('kaharesource_property',
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=50), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['kaharesource.resource_id'], ),
    sa.PrimaryKeyConstraint('resource_id', 'key')
    )
    op.create_index('created_prop_idx', 'kaharesource_property', ['created'], unique=False)
    op.create_index('resource_key_idx', 'kaharesource_property', ['key'], unique=False)
    op.create_index('updated_prop_idx', 'kaharesource_property', ['updated'], unique=False)
    op.create_table('kaharesource_source',
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('source_json', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['kaharesource.resource_id'], ),
    sa.PrimaryKeyConstraint('source_id', 'source')
    )
    op.create_index('resource_source_idx', 'kaharesource_source', ['source'], unique=False)
    op.create_table('kaharesource_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['kaharesource.resource_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('resource_type_idx', 'kaharesource_type', ['resource_type'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('resource_type_idx', table_name='kaharesource_type')
    op.drop_table('kaharesource_type')
    op.drop_index('resource_source_idx', table_name='kaharesource_source')
    op.drop_table('kaharesource_source')
    op.drop_index('updated_prop_idx', table_name='kaharesource_property')
    op.drop_index('resource_key_idx', table_name='kaharesource_property')
    op.drop_index('created_prop_idx', table_name='kaharesource_property')
    op.drop_table('kaharesource_property')
    op.drop_index('updated_kr_idx', table_name='kaharesource')
    op.drop_index('district_kr_idx', table_name='kaharesource')
    op.drop_index('created_kr_idx', table_name='kaharesource')
    op.drop_table('kaharesource')
    op.drop_index('district_vdc_idx', table_name='kaha_location')
    op.drop_index('district_name_idx', table_name='kaha_location')
    op.drop_table('kaha_location')
    ### end Alembic commands ###
