"""empty message

Revision ID: d8e5a70ed28
Revises: 2c67653c39ea
Create Date: 2015-05-02 16:19:12.865615

"""

# revision identifiers, used by Alembic.
revision = 'd8e5a70ed28'
down_revision = '2c67653c39ea'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
